Updated script

diff --git a/wp-migrate-ssh b/wp-migrate-ssh
--- a/wp-migrate-ssh
+++ b/wp-migrate-ssh
@@ -24,6 +24,7 @@ Migrate WordPress sites using ssh/rsync/wp-cli - Created by jordantrizz (https:/
         	--debug		Print debug messages
         	-f		Force even though WP installation doesn't exists, ususally due to no database.
 		-sd		Set source directory, defaults to public_html
+		-sp             Source Port
 		-dd		Set destination directory, defaults to public_html
 		-tu		Temporary URL, not used if not defined.
 		-pc		Post migration custom wp-cli commands.
@@ -42,6 +43,12 @@ preflight () {
 			exit
 		fi
 	done
+
+	echo "Checking if destination directory $dst_dir exists"
+	if [ ! -d $dst_dir ];then
+		echo "$src_dir doesn't exist"
+		exit
+	fi
 }
 
 cleanup () {
@@ -50,65 +57,71 @@ cleanup () {
 
 _debug () {
 	if [[ $debug = 1 ]]; then
-		echo "*** Debug: $@"
+		echo "*** Debug ***: $@"
 	fi
 }
 
 ssh_init () {
-	echo "Initializing SSH"	
-	# Check if there's a public SSH key.
-	echo "Checking if we have a public key"
-	if [ -f "$HOME/.ssh/id_rsa.pub" ]; then
-		echo "Found ssh key."
-		
-		# Check if the if we have know hosts.
-		echo "Checking remote connection to $src_ip."
-		sshcheck=$(ssh-keygen -F $remote_IP 2>&1)	
-		if [ $? -eq 0 ]; then
-			echo "Remote host is already in the Known Hosts file."
-		else
-			echo "Adding remote system $src_up to $HOME/.ssh/known_hosts"
-			ssh-keyscan $src_ip >> $HOME/.ssh/known_hosts
-			echo "Remote host $src_ip added to the known hosts file."
-		fi
-
-		# See if we can connect to remote host.
-		ssh_connect_test
-		if [ "$sshstatus" == "ok" ]; then
-			echo "Remote SSH Test Successful."
-		else
-			echo "SSH Test Un-successful, sending ssh key."
-			ssh-copy-id -i ~/.ssh/id_rsa.pub $src_user@$src_ip
-			if [ $? -eq 0 ]; then
-				echo "Failed to send key, falling back to password."
-				ssh_password
-			else
-				echo "Sent ssh key successfully, testing connection."
-				ssh_connect_test
-				if [ "$sshstatus" == "ok" ]; then
-		                        echo "Remote SSH Test Successful."
-		                else
-	                                echo "Failed to send key, falling back to password."
-        	                        ssh_password			
-        	                fi
-        	        fi
-		fi
+	echo "Initializing SSH Connection..."
+	
+	# Check if the if we have the host in our know hosts file.
+	echo "Checking remote connection to $src_ip."
+	ssh_check_key=$(ssh-keygen -F $remote_IP -p $src_port 2>&1)	
+	if [ $? -eq 0 ]; then
+		echo "Remote host is already in the Known Hosts file."
 	else
-		echo "No public key found."
-		ssh_password
-	fi	
+		echo "Adding remote system $src_up to $HOME/.ssh/known_hosts"
+		ssh-keyscan $src_ip >> $HOME/.ssh/known_hosts
+		echo "Remote host $src_ip added to the known hosts file."
+	fi
+
+        # Check if there's a public SSH key in home direcotry.
+        echo "Checking if we have a public key"
+        if [ -f "$HOME/.ssh/id_rsa.pub" ]; then
+                echo "...found public SSH key."
+	        ssh_key_connect_test
+        	if [ "$sshstatus" == "ok" ]; then
+                	echo "Remote SSH Test Successful with public SSH key proceeding without password authentication."			
+		else
+			echo "SSH Test Un-successfuly...trying to deploy public SSH key..."
+			ssh_deploy_key
+		fi
+        else 
+		echo "...no public SSH key found."
+		ssh_password_connect
+	fi
+
 }
 
-ssh_connect_test () {
-	sshstatus=$(ssh -o BatchMode=yes -o ConnectTimeout=5 $src_user@$src_ip echo ok 2>&1)
+ssh_key_connect_test () {
+	sshstatus=$(ssh -o BatchMode=yes -o ConnectTimeout=5 $src_user@$src_ip -p $ssh_port echo ok 2>&1)
 }
 
-ssh_password () {
+ssh_password_connect () {
         echo "Using SSH password function."
         # Let's get the SSH password. Read password interactively and save it to the environment
         read -s -p "Password to use: " SSHPASS
         export SSHPASS
         echo ""
+}
+
+ssh_deploy_key () {
+	# Deploy SSH public key
+	echo "Deploying SSH public_key"
+	ssh-copy-id -i ~/.ssh/id_rsa.pub $src_user@$src_ip -p $ssh_port
+        if [ $? -eq 0 ]; then
+		echo "Failed to send key, falling back to password."
+                ssh_password_connect
+        else
+        	echo "Sent ssh key successfully, testing connection."
+                ssh_key_connect_test
+                if [ "$sshstatus" == "ok" ]; then
+			echo "Remote SSH Test Successful."
+                else
+                	echo "Failed to send key, falling back to password."
+                        ssh_password_connect
+                fi
+        fi
 }
 
 generate_ssh_key () {
@@ -127,10 +140,10 @@ migrate_files () {
 	# Copy files. Should only show one line progress updated.
         if [ -z $SSHPASS ]; then
 		 _debug  "No \$SSHPASS so doing not passing to ssh or scp"
-		rsync -iavzh --progress --log-file=$src_ip-wp-migrate-ssh.log $src_user@$src_ip:$src_dir/wp-content $dst_dir $rsync_exclude
+		rsync -iavzh --progress --log-file=$src_ip-wp-migrate-ssh.log -e "ssh -p $src_port" $src_user@$src_ip:$src_dir/wp-content $dst_dir $rsync_exclude
 	else
 		 _debug  "\$SSHPASS exists so passing to ssh or scp"
-	        sshpass -p "$SSHPASS" rsync -iavzh --progress --log-file=$src_ip-wp-migrate-ssh.log $src_user@$src_ip:$src_dir/wp-content $dst_dir $rsync_exclude
+	        sshpass -p "$SSHPASS" rsync -iavzh --progress --log-file=$src_ip-wp-migrate-ssh.log -e "ssh -p $src_port" $src_user@$src_ip:$src_dir/wp-content $dst_dir $rsync_exclude
 	fi	     
  }
 
@@ -142,14 +155,14 @@ migrate_database () {
         # Grab the database. Need to fix path issues.
 	if [ -z $SSHPASS ]; then
 		_debug	"No \$SSHPASS so not passing to ssh or scp"
-                ssh -o "StrictHostKeyChecking no" $src_user@$src_ip "wp --path=$src_dir db export ~/$src_db_bkup"
-                scp -o "StrictHostKeyChecking no" $src_user@$src_ip:~/$src_user-wp-sql.sql .
+                ssh -o "StrictHostKeyChecking no" $src_user@$src_ip -p $src_port "wp --path=$src_dir db export ~/$src_db_bkup"
+                scp -o "StrictHostKeyChecking no" -P $src_port $src_user@$src_ip:~/$src_user-wp-sql.sql .
 	else 
 		_debug  "\$SSHPASS exists so passing to ssh or scp"
 		echo "Dumping database on $src_user@$src_ip"
-        	dump_db=$(sshpass -p "$SSHPASS" ssh -o "StrictHostKeyChecking no" $src_user@$src_ip "/usr/local/sbin/wp --path=$src_dir db export ~/$src_db_bkup")
+        	dump_db=$(sshpass -p "$SSHPASS" ssh -o "StrictHostKeyChecking no" $src_user@$src_ip -p $src_port "wp --path=$src_dir db export ~/$src_db_bkup")
         	if [ $? -eq 0 ]; then echo "dumpb_db successful"; else echo "dump_db failed $dump_db"; exit; fi
-	        grab_db=$(sshpass -p "$SSHPASS" scp -o "StrictHostKeyChecking no" $src_user@$src_ip:~/$src_user-wp-sql.sql .)
+	        grab_db=$(sshpass -p "$SSHPASS" scp -o "StrictHostKeyChecking no" -P $src_port $src_user@$src_ip:~/$src_user-wp-sql.sql .)
 	        _debug "$grab_db"
 	fi
         # Import the database.
@@ -200,6 +213,11 @@ case $key in
     ;;
     -sh)
     src_ip="$2"
+    shift # past argument
+    shift # past value
+    ;;
+    -sp)
+    src_port="$2"
     shift # past argument
     shift # past value
     ;;
@@ -263,17 +281,22 @@ if [[ $mode = 'm' ]]; then
 	if [ -z "$domain" ]; then echo "Missing required option -d"; exit; fi
 	if [ -z "$src_dir" ]; then src_dir="public_html"; fi
 	if [ -z "$dst_dir" ]; then dst_dir="public_html"; fi
-	echo "Mirgate method"
+	if [ -z "$src_port" ]; then src_port="22"; fi
+
+	echo "Mirgate method selected."
 	
 	# Checking if a WordPress install exists.
 	echo "Checking if a WordPress install exists in $dst_dir"
-
-	if [[ !$force = '1' ]]; then
-		if ! $(wp --path=$dst_dir core is-installed); then
-			echo "No WordPress install in $dst_dir"
-        		exit
+	if [[ ! $force = '1' ]]; then
+		wp_check=$(wp --path=$dst_dir core is-installed)
+		if [ $? -eq 0 ]; then
+        		echo "WordPress install found in $dst_dir"
+        	else
+                        echo "No WordPress install in $dst_dir"
+                        exit
         	fi
         fi
+        
 	# Start migration process.
 	echo "Start migration proces"
         ssh_init
@@ -335,10 +358,4 @@ else
 	help
 fi
 
-# Divi will fail to load if you don't update this.
-# Also need to investigate recently_edited option
-#if [ -z "$divifix" ]; then
-#	wp --path=$dst_dir option delete _transient_et_core_path 
-#fi
-# clear the exported variable containing the password
 unset SSHPASS
